//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiXmlSplitter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiXmlSplitter.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled XML Selection.
        /// </summary>
        internal static string CancelledXMLSelection {
            get {
                return ResourceManager.GetString("CancelledXMLSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Output Directory.
        /// </summary>
        internal static string ChooseOutputDirectory {
            get {
                return ResourceManager.GetString("ChooseOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Console.
        /// </summary>
        internal static string ClearConsole {
            get {
                return ResourceManager.GetString("ClearConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        internal static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load static resources.
        /// </summary>
        internal static string CouldNotLoadStaticResources {
            get {
                return ResourceManager.GetString("CouldNotLoadStaticResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read docnbr from UOW states file.
        /// </summary>
        internal static string CouldNotReadDocnbrFromUOWStatesFile {
            get {
                return ResourceManager.GetString("CouldNotReadDocnbrFromUOWStatesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read docnbr from XML.
        /// </summary>
        internal static string CouldNotReadDocnbrFromXML {
            get {
                return ResourceManager.GetString("CouldNotReadDocnbrFromXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not appear to provide valid UOW states.
        /// </summary>
        internal static string DoesNotAppearToProvideValidUOWStates {
            get {
                return ResourceManager.GetString("DoesNotAppearToProvideValidUOWStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing.
        /// </summary>
        internal static string ErrorInitializing {
            get {
                return ResourceManager.GetString("ErrorInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Split.
        /// </summary>
        internal static string ExecuteSplit {
            get {
                return ResourceManager.GetString("ExecuteSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File appears not to be plaintext.
        /// </summary>
        internal static string FileAppearsNotToBePlaintext {
            get {
                return ResourceManager.GetString("FileAppearsNotToBePlaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File did not meet expected pattern.
        /// </summary>
        internal static string FileDidNotMeetExpectedPattern {
            get {
                return ResourceManager.GetString("FileDidNotMeetExpectedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was empty or too short.
        /// </summary>
        internal static string FileWasEmptyOrTooShort {
            get {
                return ResourceManager.GetString("FileWasEmptyOrTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization was cancelled.
        /// </summary>
        internal static string InitializationWasCancelled {
            get {
                return ResourceManager.GetString("InitializationWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized XmlSplitterViewModel.
        /// </summary>
        internal static string InitializedXmlSplitterViewModel {
            get {
                return ResourceManager.GetString("InitializedXmlSplitterViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing XmlSplitterViewModel.
        /// </summary>
        internal static string InitializingXmlSplitterViewModel {
            get {
                return ResourceManager.GetString("InitializingXmlSplitterViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file chosen for units-of-work states.
        /// </summary>
        internal static string InvalidFileChosenForUnitsOfWorkStates {
            get {
                return ResourceManager.GetString("InvalidFileChosenForUnitsOfWorkStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance/Flight Manual.
        /// </summary>
        internal static string MaintenanceFlightManual {
            get {
                return ResourceManager.GetString("MaintenanceFlightManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file provided.
        /// </summary>
        internal static string NoFileProvided {
            get {
                return ResourceManager.GetString("NoFileProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        internal static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSDB Program.
        /// </summary>
        internal static string SelectCSDBProgram {
            get {
                return ResourceManager.GetString("SelectCSDBProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select units-of-work to extract by states.
        /// </summary>
        internal static string SelectUnitsOfWorkToExtractByStates {
            get {
                return ResourceManager.GetString("SelectUnitsOfWorkToExtractByStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select UOW States File.
        /// </summary>
        internal static string SelectUOWFile {
            get {
                return ResourceManager.GetString("SelectUOWFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XML File.
        /// </summary>
        internal static string SelectXMLFile {
            get {
                return ResourceManager.GetString("SelectXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Manual.
        /// </summary>
        internal static string SplitManual {
            get {
                return ResourceManager.GetString("SplitManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States File.
        /// </summary>
        internal static string StatesFile {
            get {
                return ResourceManager.GetString("StatesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file.
        /// </summary>
        internal static string TheFile {
            get {
                return ResourceManager.GetString("TheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML loading was cancelled.
        /// </summary>
        internal static string TheXMLLoadingWasCancelled {
            get {
                return ResourceManager.GetString("TheXMLLoadingWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units-of-Work.
        /// </summary>
        internal static string UnitsOfWork {
            get {
                return ResourceManager.GetString("UnitsOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML docnbr &apos;{xmlDocnbr}&apos; does not match UOW states file docnbr &apos;{uowDocnbr}&apos;.
        /// </summary>
        internal static string XMLDocnbrXmlDocnbrDoesNotMatchUOWStatesFileDocnbrUowDocnbr {
            get {
                return ResourceManager.GetString("XMLDocnbrXmlDocnbrDoesNotMatchUOWStatesFileDocnbrUowDocnbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File.
        /// </summary>
        internal static string XMLFile {
            get {
                return ResourceManager.GetString("XMLFile", resourceCulture);
            }
        }
    }
}
