//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiXmlSplitter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiXmlSplitter.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while creating a directory at &apos;{OutputDirectory}&apos;.
        /// </summary>
        internal static string AnIOErrorOccurredWhileCreatingADirectoryAtOutputDirectory {
            get {
                return ResourceManager.GetString("AnIOErrorOccurredWhileCreatingADirectoryAtOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work-in-progress exporting tool: An XML splitting application for segmenting the Bombardier flight and maintenance manuals into in-progress units of work..
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombardier Work-in-Progress XML Splitter.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted split not ready: output directory not provided.
        /// </summary>
        internal static string AttemptedSplitNotReadyOutputDirectoryNotProvided {
            get {
                return ResourceManager.GetString("AttemptedSplitNotReadyOutputDirectoryNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted split not ready: program not provided.
        /// </summary>
        internal static string AttemptedSplitNotReadyProgramNotProvided {
            get {
                return ResourceManager.GetString("AttemptedSplitNotReadyProgramNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted split not ready: unit-of-work states not provided.
        /// </summary>
        internal static string AttemptedSplitNotReadyUnitOfWorkStatesNotProvided {
            get {
                return ResourceManager.GetString("AttemptedSplitNotReadyUnitOfWorkStatesNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted split not ready: XML not provided.
        /// </summary>
        internal static string AttemptedSplitNotReadyXMLNotProvided {
            get {
                return ResourceManager.GetString("AttemptedSplitNotReadyXMLNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled XML Selection.
        /// </summary>
        internal static string CancelledXMLSelection {
            get {
                return ResourceManager.GetString("CancelledXMLSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout items are null.
        /// </summary>
        internal static string CheckoutItemsAreNull {
            get {
                return ResourceManager.GetString("CheckoutItemsAreNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Output Directory.
        /// </summary>
        internal static string ChooseOutputDirectory {
            get {
                return ResourceManager.GetString("ChooseOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Console.
        /// </summary>
        internal static string ClearConsole {
            get {
                return ResourceManager.GetString("ClearConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Secret.
        /// </summary>
        internal static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest manual found for {Program} {Manual} is {ClosestManual}.
        /// </summary>
        internal static string ClosestManualFoundForProgramManualIsClosestManual {
            get {
                return ResourceManager.GetString("ClosestManualFoundForProgramManualIsClosestManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load static resources.
        /// </summary>
        internal static string CouldNotLoadStaticResources {
            get {
                return ResourceManager.GetString("CouldNotLoadStaticResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse units-of-work states file.
        /// </summary>
        internal static string CouldNotParseUOWStatesFile {
            get {
                return ResourceManager.GetString("CouldNotParseUOWStatesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read docnbr from UOW states file.
        /// </summary>
        internal static string CouldNotReadDocnbrFromUOWStatesFile {
            get {
                return ResourceManager.GetString("CouldNotReadDocnbrFromUOWStatesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read docnbr from XML.
        /// </summary>
        internal static string CouldNotReadDocnbrFromXML {
            get {
                return ResourceManager.GetString("CouldNotReadDocnbrFromXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created output directory: &apos;{OutputDirectory}&apos;.
        /// </summary>
        internal static string CreatedOutputDirectoryOutputDirectory {
            get {
                return ResourceManager.GetString("CreatedOutputDirectoryOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating output directory: &apos;{OutputDirectory}&apos;.
        /// </summary>
        internal static string CreatingOutputDirectoryOutputDirectory {
            get {
                return ResourceManager.GetString("CreatingOutputDirectoryOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSDB Program succesfully identified from XML docnbr.
        /// </summary>
        internal static string CsdbProgramInferred {
            get {
                return ResourceManager.GetString("CsdbProgramInferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized CheckoutItems with {NumItems} items.
        /// </summary>
        internal static string DeserializedCheckoutItemsWithNumItemsItems {
            get {
                return ResourceManager.GetString("DeserializedCheckoutItemsWithNumItemsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized DocnbrManualFromProgram with {NumItems} items.
        /// </summary>
        internal static string DeserializedDocnbrManualFromProgramWithNumItemsItems {
            get {
                return ResourceManager.GetString("DeserializedDocnbrManualFromProgramWithNumItemsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized LookupEntities with {NumItems} items.
        /// </summary>
        internal static string DeserializedLookupEntitiesWithNumItemsItems {
            get {
                return ResourceManager.GetString("DeserializedLookupEntitiesWithNumItemsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized ProgramPerDocnbr with {NumItems} items.
        /// </summary>
        internal static string DeserializedProgramPerDocnbrWithNumItemsItems {
            get {
                return ResourceManager.GetString("DeserializedProgramPerDocnbrWithNumItemsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized StatesPerProgram with {NumItems} items.
        /// </summary>
        internal static string DeserializedStatesPerProgramWithNumItemsItems {
            get {
                return ResourceManager.GetString("DeserializedStatesPerProgramWithNumItemsItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not appear to provide valid unit-of-work states.
        /// </summary>
        internal static string DoesNotAppearToProvideValidUOWStates {
            get {
                return ResourceManager.GetString("DoesNotAppearToProvideValidUOWStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing.
        /// </summary>
        internal static string ErrorInitializing {
            get {
                return ResourceManager.GetString("ErrorInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading XML.
        /// </summary>
        internal static string ErrorLoadingXML {
            get {
                return ResourceManager.GetString("ErrorLoadingXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Split.
        /// </summary>
        internal static string ExecuteSplit {
            get {
                return ResourceManager.GetString("ExecuteSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load XML: &apos;{message}&apos;.
        /// </summary>
        internal static string FailedToLoadXMLMessage {
            get {
                return ResourceManager.GetString("FailedToLoadXMLMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File appears not to be plaintext.
        /// </summary>
        internal static string FileAppearsNotToBePlaintext {
            get {
                return ResourceManager.GetString("FileAppearsNotToBePlaintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File did not meet expected pattern.
        /// </summary>
        internal static string FileDidNotMeetExpectedPattern {
            get {
                return ResourceManager.GetString("FileDidNotMeetExpectedPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was empty or too short.
        /// </summary>
        internal static string FileWasEmptyOrTooShort {
            get {
                return ResourceManager.GetString("FileWasEmptyOrTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {num} units of work in the manual.
        /// </summary>
        internal static string FoundNumUnitsOfWorkInTheManual {
            get {
                return ResourceManager.GetString("FoundNumUnitsOfWorkInTheManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An isometric graphic representation of the XML splitting process.
        /// </summary>
        internal static string GraphicAlt {
            get {
                return ResourceManager.GetString("GraphicAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization was cancelled.
        /// </summary>
        internal static string InitializationWasCancelled {
            get {
                return ResourceManager.GetString("InitializationWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized XmlSplitterViewModel.
        /// </summary>
        internal static string InitializedXmlSplitterViewModel {
            get {
                return ResourceManager.GetString("InitializedXmlSplitterViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing XmlSplitterViewModel.
        /// </summary>
        internal static string InitializingXmlSplitterViewModel {
            get {
                return ResourceManager.GetString("InitializingXmlSplitterViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file chosen for units-of-work states.
        /// </summary>
        internal static string InvalidFileChosenForUnitsOfWorkStates {
            get {
                return ResourceManager.GetString("InvalidFileChosenForUnitsOfWorkStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UOW file &apos;{UowStatesFile}&apos; chosen.
        /// </summary>
        internal static string InvalidUOWFileUowStatesFileChosen {
            get {
                return ResourceManager.GetString("InvalidUOWFileUowStatesFileChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UOW file &apos;{UowStatesFile}&apos; chosen: &apos;{message}&apos;.
        /// </summary>
        internal static string InvalidUOWFileUowStatesFileChosenMessage {
            get {
                return ResourceManager.GetString("InvalidUOWFileUowStatesFileChosenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance/Flight Manual.
        /// </summary>
        internal static string MaintenanceFlightManual {
            get {
                return ResourceManager.GetString("MaintenanceFlightManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual from docnbr is null.
        /// </summary>
        internal static string ManualFromDocnbrIsNull {
            get {
                return ResourceManager.GetString("ManualFromDocnbrIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created the Application.
        /// </summary>
        internal static string MauiProgramCreateMauiApp {
            get {
                return ResourceManager.GetString("MauiProgramCreateMauiApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PickUowStatesFile} was cancelled.
        /// </summary>
        internal static string NameofPickUowStatesFileWasCancelled {
            get {
                return ResourceManager.GetString("NameofPickUowStatesFileWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file provided.
        /// </summary>
        internal static string NoFileProvided {
            get {
                return ResourceManager.GetString("NoFileProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No units-of-work selected.
        /// </summary>
        internal static string NoUOWStatesSelected {
            get {
                return ResourceManager.GetString("NoUOWStatesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        internal static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ran into an error while deserializing: &apos;{message}&apos;.
        /// </summary>
        internal static string RanIntoAnErrorWhileDeserializingMessage {
            get {
                return ResourceManager.GetString("RanIntoAnErrorWhileDeserializingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving fragments cancelled.
        /// </summary>
        internal static string SavingFragmentsCancelled {
            get {
                return ResourceManager.GetString("SavingFragmentsCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secrets.
        /// </summary>
        internal static string Secrets {
            get {
                return ResourceManager.GetString("Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CSDB Program.
        /// </summary>
        internal static string SelectCSDBProgram {
            get {
                return ResourceManager.GetString("SelectCSDBProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select units-of-work to extract by states.
        /// </summary>
        internal static string SelectUnitsOfWorkToExtractByStates {
            get {
                return ResourceManager.GetString("SelectUnitsOfWorkToExtractByStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select UOW States File.
        /// </summary>
        internal static string SelectUOWFile {
            get {
                return ResourceManager.GetString("SelectUOWFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XML File.
        /// </summary>
        internal static string SelectXMLFile {
            get {
                return ResourceManager.GetString("SelectXMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Manual.
        /// </summary>
        internal static string SplitManual {
            get {
                return ResourceManager.GetString("SplitManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splitting XML file {XmlFilePath} into {NumNodes} fragments.
        /// </summary>
        internal static string SplittingXMLFileXmlFilePathIntoNumNodesFragments {
            get {
                return ResourceManager.GetString("SplittingXMLFileXmlFilePathIntoNumNodesFragments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States File.
        /// </summary>
        internal static string StatesFile {
            get {
                return ResourceManager.GetString("StatesFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory path format &apos;{OutputDirectory}&apos; is not supported.
        /// </summary>
        internal static string TheDirectoryPathFormatOutputDirectoryIsNotSupported {
            get {
                return ResourceManager.GetString("TheDirectoryPathFormatOutputDirectoryIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory path &apos;{OutputDirectory}&apos; is invalid.
        /// </summary>
        internal static string TheDirectoryPathOutputDirectoryIsInvalid {
            get {
                return ResourceManager.GetString("TheDirectoryPathOutputDirectoryIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file.
        /// </summary>
        internal static string TheFile {
            get {
                return ResourceManager.GetString("TheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML docnbr &apos;{Docnbr}&apos; does not match the UOW docnbr &apos;{UowStatesDocnbr}&apos;.
        /// </summary>
        internal static string TheXMLDocnbrDocnbrDoesNotMatchTheUOWDocnbrUowStatesDocnbr {
            get {
                return ResourceManager.GetString("TheXMLDocnbrDocnbrDoesNotMatchTheUOWDocnbrUowStatesDocnbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML had no docnbr attribute.
        /// </summary>
        internal static string TheXMLHadNoDocnbrAttribute {
            get {
                return ResourceManager.GetString("TheXMLHadNoDocnbrAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML loading was cancelled.
        /// </summary>
        internal static string TheXMLLoadingWasCancelled {
            get {
                return ResourceManager.GetString("TheXMLLoadingWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save to write to path {output}.
        /// </summary>
        internal static string UnableToSaveToWriteToPathOutput {
            get {
                return ResourceManager.GetString("UnableToSaveToWriteToPathOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to output path.
        /// </summary>
        internal static string UnableToWriteToOutputPath {
            get {
                return ResourceManager.GetString("UnableToWriteToOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units-of-Work.
        /// </summary>
        internal static string UnitsOfWork {
            get {
                return ResourceManager.GetString("UnitsOfWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOW not parsed.
        /// </summary>
        internal static string UOWNotParsed {
            get {
                return ResourceManager.GetString("UOWNotParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing split report as {format}.
        /// </summary>
        internal static string WritingSplitReportAsFormat {
            get {
                return ResourceManager.GetString("WritingSplitReportAsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote fragment &apos;{name}&apos;.
        /// </summary>
        internal static string WroteFragmentName {
            get {
                return ResourceManager.GetString("WroteFragmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML docnbr &apos;{xmlDocnbr}&apos; does not match UOW states file docnbr &apos;{uowDocnbr}&apos;.
        /// </summary>
        internal static string XMLDocnbrXmlDocnbrDoesNotMatchUOWStatesFileDocnbrUowDocnbr {
            get {
                return ResourceManager.GetString("XMLDocnbrXmlDocnbrDoesNotMatchUOWStatesFileDocnbrUowDocnbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File.
        /// </summary>
        internal static string XMLFile {
            get {
                return ResourceManager.GetString("XMLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML load failed with &apos;{message}&apos;.
        /// </summary>
        internal static string XMLLoadFailedWithMessage {
            get {
                return ResourceManager.GetString("XMLLoadFailedWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML nodes were empty: No checkout units to export..
        /// </summary>
        internal static string XMLNodesWereEmptyNoCheckoutUnitsToExport {
            get {
                return ResourceManager.GetString("XMLNodesWereEmptyNoCheckoutUnitsToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML splitting report was written as HTML at .
        /// </summary>
        internal static string XmlSplitReportWrittenAsHtml {
            get {
                return ResourceManager.GetString("XmlSplitReportWrittenAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlSplitter.
        /// </summary>
        internal static string XmlSplitter {
            get {
                return ResourceManager.GetString("XmlSplitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to create a directory at &apos;{OutputDirectory}&apos;.
        /// </summary>
        internal static string YouDoNotHavePermissionToCreateADirectoryAtOutputDirectory {
            get {
                return ResourceManager.GetString("YouDoNotHavePermissionToCreateADirectoryAtOutputDirectory", resourceCulture);
            }
        }
    }
}
