//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaXmlSplitter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaXmlSplitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Black {
            get {
                object obj = ResourceManager.GetObject("_72_Black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Bold {
            get {
                object obj = ResourceManager.GetObject("_72_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_BoldItalic {
            get {
                object obj = ResourceManager.GetObject("_72_BoldItalic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Condensed {
            get {
                object obj = ResourceManager.GetObject("_72_Condensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_CondensedBold {
            get {
                object obj = ResourceManager.GetObject("_72_CondensedBold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Italic {
            get {
                object obj = ResourceManager.GetObject("_72_Italic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Light {
            get {
                object obj = ResourceManager.GetObject("_72_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Monospace_Bd {
            get {
                object obj = ResourceManager.GetObject("_72_Monospace_Bd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Monospace_Rg {
            get {
                object obj = ResourceManager.GetObject("_72_Monospace_Rg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _72_Regular {
            get {
                object obj = ResourceManager.GetObject("_72_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objs Version=&quot;1.1.0.1&quot; xmlns=&quot;http://schemas.microsoft.com/powershell/2004/04&quot;&gt;
        ///  &lt;Obj RefId=&quot;0&quot;&gt;
        ///    &lt;TN RefId=&quot;0&quot;&gt;
        ///      &lt;T&gt;System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Hashtable, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]&lt;/T&gt;
        ///      &lt;T&gt;System.Object&lt;/T&gt;
        ///    &lt;/TN&gt;
        ///    &lt;DCT&gt;
        ///      &lt;En&gt;
        ///        &lt;S N=&quot;Key&quot;&gt;GXPROD&lt;/S&gt;
        ///        &lt;Obj N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckoutItems {
            get {
                return ResourceManager.GetString("CheckoutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objs Version=&quot;1.1.0.1&quot; xmlns=&quot;http://schemas.microsoft.com/powershell/2004/04&quot;&gt;
        ///  &lt;Obj RefId=&quot;0&quot;&gt;
        ///    &lt;TN RefId=&quot;0&quot;&gt;
        ///      &lt;T&gt;System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocnbrManualFromProgram {
            get {
                return ResourceManager.GetString("DocnbrManualFromProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8x7oEJ6Mbd52zStVCld8O/nO7ilB1ji56jWcVJH0VpQ=.
        /// </summary>
        internal static string Entropy {
            get {
                return ResourceManager.GetString("Entropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EyeClosed {
            get {
                object obj = ResourceManager.GetObject("EyeClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EyeOpen {
            get {
                object obj = ResourceManager.GetObject("EyeOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D0E843FB0699B647B58110594B06E6057D1D07BAC0465F5FFC496A553A1DF8C.
        /// </summary>
        internal static string HashiCorpClientSecretExpectedHash {
            get {
                return ResourceManager.GetString("HashiCorpClientSecretExpectedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;client_id&quot;:&quot;9N55dmcf9CIiawUqaFMfO4f69sqHjM9N&quot;,&quot;ajs_aid&quot;:&quot;ecc2be89-04a6-472b-8adc-3624d3dc6a0b&quot;,&quot;user_id&quot;:&quot;e253f5ef-566d-458f-bf5a-a8b772f749f0&quot;,&quot;org_id&quot;:&quot;84ff43ee-a407-43cf-be28-3342f32fb62c&quot;,&quot;proj_id&quot;:&quot;93a0ec93-839f-4b93-84a3-51d10c796d8a&quot;,&quot;app_name&quot;:&quot;BaXmlSplitter&quot;}.
        /// </summary>
        internal static string HashiCorpIdentity {
            get {
                return ResourceManager.GetString("HashiCorpIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objs Version=&quot;1.1.0.1&quot; xmlns=&quot;http://schemas.microsoft.com/powershell/2004/04&quot;&gt;
        ///  &lt;Obj RefId=&quot;0&quot;&gt;
        ///    &lt;TN RefId=&quot;0&quot;&gt;
        ///      &lt;T&gt;System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Management.Automation.PSObject, System.Management.Automation, Version=7.4.0.5, C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatesPerProgramXml {
            get {
                return ResourceManager.GetString("StatesPerProgramXml", resourceCulture);
            }
        }
    }
}
