//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaXmlSplitter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaXmlSplitter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrows {
            get {
                object obj = ResourceManager.GetObject("arrows", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fb61b2d7-0d45-43c0-bc85-95701ceb3331.
        /// </summary>
        internal static string AzureAppID {
            get {
                return ResourceManager.GetString("AzureAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A09A0E1E9E7FEB5A2A649418D547BF3DDB9259C6B32FF8809C3A5657E7C30A67.
        /// </summary>
        internal static string AzureSecretExpectedHash {
            get {
                return ResourceManager.GetString("AzureSecretExpectedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaXmlSplitter.
        /// </summary>
        internal static string AzureServicePrincipal {
            get {
                return ResourceManager.GetString("AzureServicePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1A76B2D2BE05A0FAA0CBC01C024C0A6EA299CC89B7641EE431F970181B10878.
        /// </summary>
        internal static string BaOraConnectionStringExpectedHash {
            get {
                return ResourceManager.GetString("BaOraConnectionStringExpectedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objs Version=&quot;1.1.0.1&quot; xmlns=&quot;http://schemas.microsoft.com/powershell/2004/04&quot;&gt;
        ///  &lt;Obj RefId=&quot;0&quot;&gt;
        ///    &lt;TN RefId=&quot;0&quot;&gt;
        ///      &lt;T&gt;System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Hashtable, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]&lt;/T&gt;
        ///      &lt;T&gt;System.Object&lt;/T&gt;
        ///    &lt;/TN&gt;
        ///    &lt;DCT&gt;
        ///      &lt;En&gt;
        ///        &lt;S N=&quot;Key&quot;&gt;GXPROD&lt;/S&gt;
        ///        &lt;Obj N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckoutItems {
            get {
                return ResourceManager.GetString("CheckoutItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objs Version=&quot;1.1.0.1&quot; xmlns=&quot;http://schemas.microsoft.com/powershell/2004/04&quot;&gt;
        ///  &lt;Obj RefId=&quot;0&quot;&gt;
        ///    &lt;TN RefId=&quot;0&quot;&gt;
        ///      &lt;T&gt;System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DocnbrManualFromProgram {
            get {
                return ResourceManager.GetString("DocnbrManualFromProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8x7oEJ6Mbd52zStVCld8O/nO7ilB1ji56jWcVJH0VpQ=.
        /// </summary>
        internal static string Entropy {
            get {
                return ResourceManager.GetString("Entropy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EyeClosed {
            get {
                object obj = ResourceManager.GetObject("EyeClosed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EyeOpen {
            get {
                object obj = ResourceManager.GetObject("EyeOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D0E843FB0699B647B58110594B06E6057D1D07BAC0465F5FFC496A553A1DF8C.
        /// </summary>
        internal static string HashiCorpClientSecretExpectedHash {
            get {
                return ResourceManager.GetString("HashiCorpClientSecretExpectedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] HashiCorpIdentity {
            get {
                object obj = ResourceManager.GetObject("HashiCorpIdentity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Objs Version=&quot;1.1.0.1&quot; xmlns=&quot;http://schemas.microsoft.com/powershell/2004/04&quot;&gt;
        ///  &lt;Obj RefId=&quot;0&quot;&gt;
        ///    &lt;TN RefId=&quot;0&quot;&gt;
        ///      &lt;T&gt;System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Collections.Generic.Dictionary`2[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Management.Automation.PSObject, System.Management.Automation, Version=7.4.0.5, C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatesPerProgram {
            get {
                return ResourceManager.GetString("StatesPerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1502C7FE00BCF6E9A4312C34338080D462CE14B841087929A75C16EBA21B659F.
        /// </summary>
        internal static string StorageAccountKeyOneExpectedHash {
            get {
                return ResourceManager.GetString("StorageAccountKeyOneExpectedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18876E1A9946F6965B2BDCB503996EF5C253C2C3E281174558C86C67910561E1.
        /// </summary>
        internal static string StorageAccountKeyTwoExpectedHash {
            get {
                return ResourceManager.GetString("StorageAccountKeyTwoExpectedHash", resourceCulture);
            }
        }
    }
}
